M48
; DRILL file {KiCad (6.0.4-0)} date Monday, 01 April 2024 at 10:42:20 am
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-01T10:42:20+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.9055Y-2.6398
X4.0335Y-2.1142
X5.8445Y-2.1181
T0
M30
