M48
; DRILL file {KiCad (6.0.4-0)} date Saturday, 06 April 2024 at 09:11:46 am
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-06T09:11:46+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
%
G90
G05
T1
X4.3228Y-1.1299
X4.9213Y-1.1299
X6.815Y-1.1319
T0
M30
